Repository ViridianVille/ViridianVille.github.io, pull requests merged in 2022-09, with the labels that each got.

#1 VIR-3-arrange-github-pages-backend
  .github/workflows/pages.yml
  .gitignore
  404.html
  Gemfile
  Gemfile.lock
  _config.yml
  _posts/2022-09-18-welcome-to-jekyll.markdown
  about.markdown
  index.markdown
Labels: enhancement

#8 VIR-5 Author work and Blog Replace
  .DS_Store
  .idea/workspace.xml
  _config.yml
  _data/authors.yml
  _posts/2022-09-18-What-is-Project-Viridian.markdown
  _posts/2022-09-18-welcome-to-jekyll.markdown
  assets/.DS_Store
  assets/images/dab_dragon.png
  assets/images/katbio.jpeg
  assets/images/tifabio.png
Labels: documentation

#9 VIR-7-organise-posts-to-appear
  _config.yml
  _pages/categories.markdown
  _pages/page-archive.markdown
  _pages/sitemap.markdown
  _pages/year-archive-grid.markdown
  _posts/2022-09-18-What-is-Project-Viridian.markdown
  index.html
  splash.markdown
Labels: design
